# Generated by Django 4.2.7 on 2024-05-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0004_alter_article_author_alter_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('business', 'Business'), ('entertainment', 'Entertainment'), ('health', 'Health'), ('science', 'Science'), ('sports', 'Sports'), ('technology', 'Technology')], default='general', max_length=255),
        ),
    ]
